import os
from dotenv import load_dotenv

load_dotenv()

# API KEYS
PRISM_API_KEY = os.getenv("PRISM_API_KEY")
KRAKEN_API_KEY = os.getenv("KRAKEN_API_KEY")
KRAKEN_API_SECRET = os.getenv("KRAKEN_API_SECRET")

# TRADING
TRADING_PAIR = "BTC/USD"
CHECK_INTERVAL = 300

# RISK MANAGEMENT
MAX_TRADE_USD = 100
MAX_RISK_PERCENT = 0.02
DAILY_LOSS_LIMIT_USD = 50
MAX_OPEN_POSITIONS = 3
STOP_LOSS_PERCENT = 0.03
TAKE_PROFIT_PERCENT = 0.05

# STRATEGY
BUY_THRESHOLD = 60
SELL_THRESHOLD = -60

# PRISM
PRISM_BASE_URL = "https://api.prismapi.ai"

# LOGGING
LOG_FILE = "logs/trades.log"
